<?php
session_start();
include '../config/db.php';
require_once __DIR__ . '/report_helpers.php';

eventify_require_role('admin');

$filters = eventify_reports_normalize_filters($_GET);
$report = eventify_reports_data($conn, $filters);
$admin = eventify_reports_current_admin($conn);
$monthlyTemplate = $filters['report_type'] === 'monthly'
    ? eventify_reports_monthly_template_data($report, $filters)
    : null;
$format = strtolower(trim($_GET['format'] ?? 'csv'));
$reportTitle = eventify_reports_title($filters);
$dateLabel = eventify_reports_date_label($filters);
$generatedAt = date('M d, Y h:i A');
$filenameBase = 'eventify-' . $filters['report_type'] . '-sales-report-' . date('Ymd-His');

function eventify_reports_plain_money($amount) {
    return 'PHP ' . number_format((float) $amount, 2);
}

function eventify_reports_compact_money($amount) {
    return 'P' . number_format((float) $amount, 2);
}

function eventify_reports_output_csv($report, $reportTitle, $dateLabel, $admin, $generatedAt, $filenameBase, $monthlyTemplate = null) {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filenameBase . '.csv"');

    $output = fopen('php://output', 'w');

    fputcsv($output, ['Eventify Event Reservation and Management System']);
    fputcsv($output, [$reportTitle]);
    fputcsv($output, ['Selected Date Range', $dateLabel]);
    fputcsv($output, ['Generated By', $admin['name']]);
    fputcsv($output, ['Date Generated', $generatedAt]);
    fputcsv($output, []);

    fputcsv($output, ['Summary Totals']);
    fputcsv($output, ['Total Approved Transactions', $report['totals']['approved_transactions']]);
    fputcsv($output, ['Total Reservations', $report['totals']['total_reservations']]);
    fputcsv($output, ['Total Events Booked', $report['totals']['total_events_booked']]);
    fputcsv($output, ['Total Sales Amount', number_format((float) $report['totals']['total_sales'], 2, '.', '')]);
    fputcsv($output, ['Total Paid Amount', number_format((float) $report['totals']['total_paid'], 2, '.', '')]);
    fputcsv($output, ['Remaining Balance', number_format((float) $report['totals']['remaining_balance'], 2, '.', '')]);
    fputcsv($output, ['Cancelled Transactions Count', $report['totals']['cancelled_count']]);
    fputcsv($output, ['Rejected Transactions Count', $report['totals']['rejected_count']]);
    fputcsv($output, []);

    if ($monthlyTemplate) {
        fputcsv($output, ['Monthly Sales Performance']);
        fputcsv($output, ['Sale Type', 'Reservation Count', 'Event Count', 'Total Sales', 'Paid Amount', 'Balance']);

        foreach ($monthlyTemplate['sales_performance'] as $performance) {
            fputcsv($output, [
                $performance['label'],
                $performance['values']['reservation_count'],
                $performance['values']['event_count'],
                number_format((float) $performance['values']['total_sales'], 2, '.', ''),
                number_format((float) $performance['values']['total_paid'], 2, '.', ''),
                number_format((float) $performance['values']['remaining_balance'], 2, '.', ''),
            ]);
        }

        fputcsv($output, []);
        fputcsv($output, ['Monthly Sales By Day']);
        fputcsv($output, ['Day', 'Count', 'Value']);

        foreach ($monthlyTemplate['sales_by_day'] as $day) {
            fputcsv($output, [
                $day['label'],
                $day['count'],
                number_format((float) $day['sales'], 2, '.', ''),
            ]);
        }

        fputcsv($output, []);
    }

    fputcsv($output, ['Approved Transactions Table']);
    fputcsv($output, [
        'Receipt/Reference Number',
        'Client Name',
        'Event Type/Package',
        'Event Date',
        'Reservation Date',
        'Total Amount',
        'Amount Paid',
        'Remaining Balance',
        'Payment Method',
        'Reservation Status',
        'Approved By',
        'Date Approved',
    ]);

    foreach ($report['rows'] as $row) {
        fputcsv($output, [
            $row['display_reference'],
            $row['display_client_name'],
            $row['display_event_package'],
            eventify_reports_format_date($row['event_date']),
            eventify_reports_format_date($row['created_at']),
            number_format((float) $row['total_amount'], 2, '.', ''),
            number_format((float) $row['paid_amount'], 2, '.', ''),
            number_format((float) $row['remaining_balance'], 2, '.', ''),
            $row['display_payment_method'],
            $row['status'],
            $row['approved_by'],
            eventify_reports_format_datetime($row['date_approved']),
        ]);
    }

    fputcsv($output, []);
    fputcsv($output, ['Payment Summary Table']);
    fputcsv($output, ['Payment Method', 'Number of Transactions', 'Total Sales', 'Total Paid', 'Total Remaining Balance']);

    foreach ($report['payment_summary'] as $summary) {
        fputcsv($output, [
            $summary['payment_method'],
            $summary['transactions'],
            number_format((float) $summary['total_sales'], 2, '.', ''),
            number_format((float) $summary['total_paid'], 2, '.', ''),
            number_format((float) $summary['remaining_balance'], 2, '.', ''),
        ]);
    }

    fputcsv($output, []);
    fputcsv($output, ['Event Category Summary']);
    fputcsv($output, ['Event Type/Package', 'Number of Approved Reservations', 'Total Sales']);

    foreach ($report['category_summary'] as $summary) {
        fputcsv($output, [
            $summary['event_package'],
            $summary['reservations'],
            number_format((float) $summary['total_sales'], 2, '.', ''),
        ]);
    }

    fclose($output);
    exit();
}

function eventify_reports_pdf_escape($value) {
    $value = str_replace(["\r", "\n", "\t"], [' ', ' ', ' '], (string) $value);
    $value = preg_replace('/[^\x20-\x7E]/', '', $value);

    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value);
}

function eventify_reports_pdf_number($value) {
    return rtrim(rtrim(sprintf('%.2F', (float) $value), '0'), '.');
}

function eventify_reports_pdf_text_width($text, $size) {
    return strlen((string) $text) * $size * 0.46;
}

function eventify_reports_pdf_text(&$content, $x, $y, $text, $size = 8, $font = 'F1', $align = 'left', $rgb = [0, 0, 0]) {
    $text = (string) $text;

    if ($align === 'right') {
        $x -= eventify_reports_pdf_text_width($text, $size);
    } elseif ($align === 'center') {
        $x -= eventify_reports_pdf_text_width($text, $size) / 2;
    }

    $content .= sprintf("%.3F %.3F %.3F rg\n", $rgb[0], $rgb[1], $rgb[2]);
    $content .= "BT\n/" . $font . " " . eventify_reports_pdf_number($size) . " Tf\n";
    $content .= eventify_reports_pdf_number($x) . " " . eventify_reports_pdf_number($y) . " Td\n";
    $content .= '(' . eventify_reports_pdf_escape($text) . ") Tj\nET\n";
}

function eventify_reports_pdf_line(&$content, $x1, $y1, $x2, $y2, $width = 0.5, $rgb = [0, 0, 0], $dotted = false) {
    $content .= sprintf("%.3F %.3F %.3F RG\n", $rgb[0], $rgb[1], $rgb[2]);
    $content .= eventify_reports_pdf_number($width) . " w\n";
    $content .= $dotted ? "[1 3] 0 d\n" : "[] 0 d\n";
    $content .= eventify_reports_pdf_number($x1) . " " . eventify_reports_pdf_number($y1) . " m\n";
    $content .= eventify_reports_pdf_number($x2) . " " . eventify_reports_pdf_number($y2) . " l\nS\n[] 0 d\n";
}

function eventify_reports_pdf_rect(&$content, $x, $y, $width, $height, $lineWidth = 0.5, $rgb = [0, 0, 0]) {
    $content .= sprintf("%.3F %.3F %.3F RG\n", $rgb[0], $rgb[1], $rgb[2]);
    $content .= eventify_reports_pdf_number($lineWidth) . " w\n";
    $content .= eventify_reports_pdf_number($x) . " " . eventify_reports_pdf_number($y) . " " . eventify_reports_pdf_number($width) . " " . eventify_reports_pdf_number($height) . " re\nS\n";
}

function eventify_reports_pdf_fit($text, $maxChars) {
    $text = trim(preg_replace('/\s+/', ' ', (string) $text));

    if (strlen($text) <= $maxChars) {
        return $text;
    }

    return substr($text, 0, max(0, $maxChars - 1)) . '.';
}

function eventify_reports_pdf_table(&$content, $x, $y, $columns, $rows, $rowHeight = 13, $fontSize = 6.8) {
    $tableWidth = array_sum(array_column($columns, 'width'));
    $blue = [0.27, 0.59, 0.78];
    $gray = [0.55, 0.55, 0.55];

    foreach ($columns as $column) {
        $align = $column['align'] ?? 'left';
        $textX = $x + ($align === 'right' ? $column['width'] - 2 : 2);
        eventify_reports_pdf_text($content, $textX, $y, $column['label'], $fontSize, 'F1', $align, [0, 0, 0]);
        $x += $column['width'];
    }

    $x -= $tableWidth;
    eventify_reports_pdf_line($content, $x, $y - 4, $x + $tableWidth, $y - 4, 0.7, $gray);
    $y -= $rowHeight;

    foreach ($rows as $row) {
        $isTotal = !empty($row['total']);
        $values = $row['values'];
        $currentX = $x;

        foreach ($columns as $index => $column) {
            $align = $column['align'] ?? 'left';
            $value = eventify_reports_pdf_fit($values[$index] ?? '', $column['chars'] ?? 20);
            $textX = $currentX + ($align === 'right' ? $column['width'] - 2 : 2);
            eventify_reports_pdf_text($content, $textX, $y, $value, $fontSize, $isTotal ? 'F2' : 'F1', $align, [0, 0, 0]);
            $currentX += $column['width'];
        }

        eventify_reports_pdf_line($content, $x, $y - 4, $x + $tableWidth, $y - 4, $isTotal ? 0.65 : 0.35, $gray, !$isTotal);
        $y -= $rowHeight;
    }

    return $y;
}

function eventify_reports_output_content_pdf($pageContents, $filenameBase, $mediaBox = '[0 0 612 792]') {
    $objects = [];
    $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    $objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
    $objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';
    $pageObjectIds = [];
    $nextObjectId = 5;

    foreach ($pageContents as $content) {
        $pageObjectId = $nextObjectId++;
        $contentObjectId = $nextObjectId++;
        $pageObjectIds[] = $pageObjectId;
        $objects[$contentObjectId] = "<< /Length " . strlen($content) . " >>\nstream\n" . $content . "\nendstream";
        $objects[$pageObjectId] = "<< /Type /Page /Parent 2 0 R /MediaBox $mediaBox /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents " . $contentObjectId . " 0 R >>";
    }

    $kids = array_map(function ($id) {
        return $id . ' 0 R';
    }, $pageObjectIds);
    $objects[2] = '<< /Type /Pages /Count ' . count($pageObjectIds) . ' /Kids [' . implode(' ', $kids) . '] >>';
    ksort($objects);

    $pdf = "%PDF-1.4\n";
    $offsets = [];

    foreach ($objects as $id => $object) {
        $offsets[$id] = strlen($pdf);
        $pdf .= $id . " 0 obj\n" . $object . "\nendobj\n";
    }

    $xrefOffset = strlen($pdf);
    $objectCount = max(array_keys($objects)) + 1;
    $pdf .= "xref\n0 " . $objectCount . "\n";
    $pdf .= "0000000000 65535 f \n";

    for ($i = 1; $i < $objectCount; $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i] ?? 0);
    }

    $pdf .= "trailer\n<< /Size " . $objectCount . " /Root 1 0 R >>\n";
    $pdf .= "startxref\n" . $xrefOffset . "\n%%EOF";

    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filenameBase . '.pdf"');
    header('Content-Length: ' . strlen($pdf));
    echo $pdf;
    exit();
}

function eventify_reports_output_monthly_template_pdf($report, $filters, $monthlyTemplate, $dateLabel, $admin, $generatedAt, $filenameBase) {
    $content = "";
    $blue = [0.27, 0.59, 0.78];
    $yellow = [0.92, 0.63, 0.03];
    $gray = [0.55, 0.55, 0.55];
    $left = 42;
    $right = 570;

    eventify_reports_pdf_rect($content, 18, 18, 576, 756, 1.4, $yellow);
    eventify_reports_pdf_text($content, $left, 748, 'This monthly sales report shows approved reservations with verified payments for the selected month.', 7.5, 'F2', 'left', $blue);
    eventify_reports_pdf_text($content, $left, 729, 'Eventify Event Reservation and Management System', 5.8, 'F1', 'left', $blue);
    eventify_reports_pdf_text($content, $left, 710, 'Monthly Sales Report', 22, 'F1');
    eventify_reports_pdf_text($content, $right, 716, $dateLabel, 13, 'F1', 'right');
    eventify_reports_pdf_text($content, $right, 704, 'Generated ' . $generatedAt, 4.8, 'F1', 'right', [0.35, 0.35, 0.35]);
    eventify_reports_pdf_line($content, $left, 692, $right, 692, 1.4);

    eventify_reports_pdf_text($content, $left, 664, 'Sales Performance', 15.5, 'F1');
    eventify_reports_pdf_text($content, 255, 668, 'Approved reservations with verified payments only.', 7, 'F2', 'left', $blue);
    $salesRows = [];
    foreach ($monthlyTemplate['sales_performance'] as $performance) {
        $salesRows[] = [
            'total' => !empty($performance['is_total']),
            'values' => [
                $performance['label'],
                number_format($performance['values']['reservation_count']),
                number_format($performance['values']['event_count']),
                eventify_reports_plain_money($performance['values']['total_sales']),
                eventify_reports_plain_money($performance['values']['total_paid']),
                eventify_reports_plain_money($performance['values']['remaining_balance']),
            ],
        ];
    }
    eventify_reports_pdf_table($content, $left, 640, [
        ['label' => 'Sale Type', 'width' => 160, 'chars' => 28],
        ['label' => 'Reservation Count', 'width' => 70, 'align' => 'right', 'chars' => 10],
        ['label' => 'Event Count', 'width' => 60, 'align' => 'right', 'chars' => 10],
        ['label' => 'Total Sales', 'width' => 80, 'align' => 'right', 'chars' => 15],
        ['label' => 'Paid Amount', 'width' => 80, 'align' => 'right', 'chars' => 15],
        ['label' => 'Balance', 'width' => 78, 'align' => 'right', 'chars' => 15],
    ], $salesRows, 15, 5.8);

    eventify_reports_pdf_text($content, $left, 548, 'Payment Performance', 15.5, 'F1');
    eventify_reports_pdf_text($content, $left, 538, 'Verified payments grouped by method.', 7, 'F2', 'left', $blue);
    $paymentRows = [];
    foreach ($report['payment_summary'] as $summary) {
        $paymentRows[] = [
            'values' => [
                $summary['payment_method'],
                number_format($summary['transactions']),
                eventify_reports_plain_money($summary['total_sales']),
                eventify_reports_plain_money($summary['total_paid']),
                eventify_reports_plain_money($summary['remaining_balance']),
            ],
        ];
    }
    $paymentRows[] = [
        'total' => true,
        'values' => [
            'Total',
            number_format($report['totals']['approved_transactions']),
            eventify_reports_plain_money($report['totals']['total_sales']),
            eventify_reports_plain_money($report['totals']['total_paid']),
            eventify_reports_plain_money($report['totals']['remaining_balance']),
        ],
    ];
    eventify_reports_pdf_table($content, $left, 520, [
        ['label' => 'Payment Method', 'width' => 100, 'chars' => 18],
        ['label' => 'Count', 'width' => 48, 'align' => 'right', 'chars' => 8],
        ['label' => 'Sales', 'width' => 68, 'align' => 'right', 'chars' => 12],
        ['label' => 'Paid', 'width' => 68, 'align' => 'right', 'chars' => 12],
        ['label' => 'Balance', 'width' => 68, 'align' => 'right', 'chars' => 12],
    ], $paymentRows, 13, 5.6);

    eventify_reports_pdf_text($content, $left, 427, 'Event Category Summary', 15.5, 'F1');
    eventify_reports_pdf_text($content, $left, 417, 'Approved paid reservations by event/package.', 7, 'F2', 'left', $blue);
    $categoryRows = [];
    foreach ($report['category_summary'] as $summary) {
        $categoryRows[] = [
            'values' => [
                $summary['event_package'],
                number_format($summary['reservations']),
                eventify_reports_plain_money($summary['total_sales']),
            ],
        ];
    }
    $categoryRows[] = [
        'total' => true,
        'values' => [
            'Total',
            number_format($report['totals']['total_reservations']),
            eventify_reports_plain_money($report['totals']['total_sales']),
        ],
    ];
    eventify_reports_pdf_table($content, $left, 399, [
        ['label' => 'Event Type / Package', 'width' => 190, 'chars' => 34],
        ['label' => 'Count', 'width' => 62, 'align' => 'right', 'chars' => 10],
        ['label' => 'Total Sales', 'width' => 100, 'align' => 'right', 'chars' => 15],
    ], $categoryRows, 13, 5.6);

    eventify_reports_pdf_text($content, $left, 284, 'Report Summary', 15.5, 'F1');
    $summaryY = 265;
    foreach ($monthlyTemplate['activity_summary'] as $item) {
        eventify_reports_pdf_text($content, $left + 2, $summaryY, $item['label'], 6.4);
        eventify_reports_pdf_text($content, 392, $summaryY, $item['value'], 6.4, 'F2', 'right');
        eventify_reports_pdf_line($content, $left, $summaryY - 4, 392, $summaryY - 4, 0.35, $gray, true);
        $summaryY -= 14;
    }
    eventify_reports_pdf_text($content, $left + 2, $summaryY, 'Generated By', 6.4);
    eventify_reports_pdf_text($content, 392, $summaryY, $admin['name'], 6.4, 'F2', 'right');
    eventify_reports_pdf_line($content, $left, $summaryY - 4, 392, $summaryY - 4, 0.35, $gray, true);

    $dayTableX = 402;
    eventify_reports_pdf_text($content, $dayTableX, 548, 'Sales By Day', 15.5, 'F1');
    eventify_reports_pdf_text($content, $dayTableX, 538, 'Reservation approval date within the month.', 7, 'F2', 'left', $blue);
    $dayRows = [];
    foreach ($monthlyTemplate['sales_by_day'] as $day) {
        $dayRows[] = [
            'values' => [
                $day['label'],
                number_format($day['count']),
                eventify_reports_compact_money($day['sales']),
            ],
        ];
    }
    eventify_reports_pdf_table($content, $dayTableX, 520, [
        ['label' => 'Day', 'width' => 56, 'chars' => 10],
        ['label' => 'Count', 'width' => 34, 'align' => 'right', 'chars' => 7],
        ['label' => 'Value', 'width' => 78, 'align' => 'right', 'chars' => 13],
    ], $dayRows, 11.2, 5.2);

    eventify_reports_output_content_pdf([$content], $filenameBase);
}

function eventify_reports_pdf_row($values, $widths) {
    $cells = [];

    foreach ($values as $index => $value) {
        $width = $widths[$index] ?? 12;
        $text = preg_replace('/\s+/', ' ', trim((string) $value));

        if (strlen($text) > $width) {
            $text = substr($text, 0, max(0, $width - 1)) . '.';
        }

        $cells[] = str_pad($text, $width);
    }

    return rtrim(implode(' ', $cells));
}

function eventify_reports_pdf_lines($report, $reportTitle, $dateLabel, $admin, $generatedAt, $monthlyTemplate = null) {
    $lines = [
        'Eventify Event Reservation and Management System',
        $reportTitle,
        'Selected Date Range: ' . $dateLabel,
        'Generated By: ' . $admin['name'],
        'Date Generated: ' . $generatedAt,
        '',
        'Summary Totals',
        'Total Approved Transactions: ' . $report['totals']['approved_transactions'],
        'Total Reservations: ' . $report['totals']['total_reservations'],
        'Total Events Booked: ' . $report['totals']['total_events_booked'],
        'Total Sales Amount: ' . eventify_reports_plain_money($report['totals']['total_sales']),
        'Total Paid Amount: ' . eventify_reports_plain_money($report['totals']['total_paid']),
        'Remaining Balance: ' . eventify_reports_plain_money($report['totals']['remaining_balance']),
        'Cancelled Transactions Count: ' . $report['totals']['cancelled_count'],
        'Rejected Transactions Count: ' . $report['totals']['rejected_count'],
        '',
    ];

    if ($monthlyTemplate) {
        $lines[] = 'Sales Performance';
        $salesWidths = [28, 12, 10, 16, 16, 16];
        $lines[] = eventify_reports_pdf_row(['Sale Type', 'Reservations', 'Events', 'Total Sales', 'Paid Amount', 'Balance'], $salesWidths);

        foreach ($monthlyTemplate['sales_performance'] as $performance) {
            $lines[] = eventify_reports_pdf_row([
                $performance['label'],
                $performance['values']['reservation_count'],
                $performance['values']['event_count'],
                eventify_reports_plain_money($performance['values']['total_sales']),
                eventify_reports_plain_money($performance['values']['total_paid']),
                eventify_reports_plain_money($performance['values']['remaining_balance']),
            ], $salesWidths);
        }

        $lines[] = '';
        $lines[] = 'Sales By Day';
        $dayWidths = [12, 10, 16];
        $lines[] = eventify_reports_pdf_row(['Day', 'Count', 'Value'], $dayWidths);

        foreach ($monthlyTemplate['sales_by_day'] as $day) {
            $lines[] = eventify_reports_pdf_row([
                $day['label'],
                $day['count'],
                eventify_reports_plain_money($day['sales']),
            ], $dayWidths);
        }

        $lines[] = '';
    }

    $lines[] = 'Approved Transactions Table';

    $transactionWidths = [16, 16, 20, 11, 11, 12, 12, 12, 14, 10, 14, 18];
    $lines[] = eventify_reports_pdf_row([
        'Reference',
        'Client',
        'Event/Package',
        'Event Date',
        'Res Date',
        'Total',
        'Paid',
        'Balance',
        'Method',
        'Status',
        'Approved By',
        'Date Approved',
    ], $transactionWidths);

    if (empty($report['rows'])) {
        $lines[] = 'No approved and verified paid transactions found for this report.';
    }

    foreach ($report['rows'] as $row) {
        $lines[] = eventify_reports_pdf_row([
            $row['display_reference'],
            $row['display_client_name'],
            $row['display_event_package'],
            eventify_reports_format_date($row['event_date']),
            eventify_reports_format_date($row['created_at']),
            eventify_reports_plain_money($row['total_amount']),
            eventify_reports_plain_money($row['paid_amount']),
            eventify_reports_plain_money($row['remaining_balance']),
            $row['display_payment_method'],
            $row['status'],
            $row['approved_by'],
            eventify_reports_format_datetime($row['date_approved']),
        ], $transactionWidths);
    }

    $lines[] = '';
    $lines[] = 'Payment Summary Table';
    $paymentWidths = [24, 14, 16, 16, 18];
    $lines[] = eventify_reports_pdf_row(['Payment Method', 'Transactions', 'Total Sales', 'Total Paid', 'Remaining'], $paymentWidths);

    if (empty($report['payment_summary'])) {
        $lines[] = 'No payment summary available.';
    }

    foreach ($report['payment_summary'] as $summary) {
        $lines[] = eventify_reports_pdf_row([
            $summary['payment_method'],
            $summary['transactions'],
            eventify_reports_plain_money($summary['total_sales']),
            eventify_reports_plain_money($summary['total_paid']),
            eventify_reports_plain_money($summary['remaining_balance']),
        ], $paymentWidths);
    }

    $lines[] = '';
    $lines[] = 'Event Category Summary';
    $categoryWidths = [42, 18, 18];
    $lines[] = eventify_reports_pdf_row(['Event Type/Package', 'Approved Reservations', 'Total Sales'], $categoryWidths);

    if (empty($report['category_summary'])) {
        $lines[] = 'No category summary available.';
    }

    foreach ($report['category_summary'] as $summary) {
        $lines[] = eventify_reports_pdf_row([
            $summary['event_package'],
            $summary['reservations'],
            eventify_reports_plain_money($summary['total_sales']),
        ], $categoryWidths);
    }

    return $lines;
}

function eventify_reports_output_pdf($lines, $filenameBase) {
    $pages = array_chunk($lines, 62);

    if (empty($pages)) {
        $pages = [['No report data.']];
    }

    $objects = [];
    $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    $objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>';

    $pageObjectIds = [];
    $nextObjectId = 4;

    foreach ($pages as $pageLines) {
        $pageObjectId = $nextObjectId++;
        $contentObjectId = $nextObjectId++;
        $pageObjectIds[] = $pageObjectId;

        $content = "BT\n/F1 6 Tf\n30 570 Td\n8 TL\n";

        foreach ($pageLines as $line) {
            $content .= '(' . eventify_reports_pdf_escape($line) . ") Tj\nT*\n";
        }

        $content .= "ET";
        $objects[$contentObjectId] = "<< /Length " . strlen($content) . " >>\nstream\n" . $content . "\nendstream";
        $objects[$pageObjectId] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /Resources << /Font << /F1 3 0 R >> >> /Contents " . $contentObjectId . " 0 R >>";
    }

    $kids = array_map(function ($id) {
        return $id . ' 0 R';
    }, $pageObjectIds);
    $objects[2] = '<< /Type /Pages /Count ' . count($pageObjectIds) . ' /Kids [' . implode(' ', $kids) . '] >>';

    ksort($objects);

    $pdf = "%PDF-1.4\n";
    $offsets = [];

    foreach ($objects as $id => $object) {
        $offsets[$id] = strlen($pdf);
        $pdf .= $id . " 0 obj\n" . $object . "\nendobj\n";
    }

    $xrefOffset = strlen($pdf);
    $objectCount = max(array_keys($objects)) + 1;
    $pdf .= "xref\n0 " . $objectCount . "\n";
    $pdf .= "0000000000 65535 f \n";

    for ($i = 1; $i < $objectCount; $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i] ?? 0);
    }

    $pdf .= "trailer\n<< /Size " . $objectCount . " /Root 1 0 R >>\n";
    $pdf .= "startxref\n" . $xrefOffset . "\n%%EOF";

    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filenameBase . '.pdf"');
    header('Content-Length: ' . strlen($pdf));
    echo $pdf;
    exit();
}

if ($format === 'pdf') {
    if ($monthlyTemplate) {
        eventify_reports_output_monthly_template_pdf($report, $filters, $monthlyTemplate, $dateLabel, $admin, $generatedAt, $filenameBase);
    }

    eventify_reports_output_pdf(
        eventify_reports_pdf_lines($report, $reportTitle, $dateLabel, $admin, $generatedAt, $monthlyTemplate),
        $filenameBase
    );
}

eventify_reports_output_csv($report, $reportTitle, $dateLabel, $admin, $generatedAt, $filenameBase, $monthlyTemplate);

?>
